dist: xenial
language: php

matrix:
  fast_finish: true
  include:
    - php: 8.0

env:
  - APP_ENV=testing

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - mysql -e 'create database landlord;'

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --path=database/migrations/landlord --database=landlord --force

script:
  - echo "Skipping tests"

sudo: required
