version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=letmein
      - MYSQL_DATABASE=landlord
    ports:
      - "3306:3306"
    volumes:
      - mydata:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  echo-server:
    image: oanhnn/laravel-echo-server:latest
    ports:
      - "6001:6001"
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  mydata:
